### ISSUE TITLE
Not working on heroku (Heroku Deploy Button)

### ISSUE THREAD

**Issue by chammiii** [jagrit007/Telegram-CloneBot#2]
Kindly help to deploy and working on heroku
Thanks in advance

**Comment by jagrit007** [comment]
Alright, will look into it. Can you put logs here?

**Comment by chammiii** [comment]
Hang on /clone Command
Like
![Screenshot_2020-08-14-23-59-52-203_org telegram messenger](https://user-images.githubusercontent.com/23624044/90281486-47d1b400-de8a-11ea-9a5f-93e38959ad43.jpg)

**Comment by chammiii** [comment]
Hang after /clone command 
Like
![Screenshot_2020-08-15-00-01-08-918_org telegram messenger](https://user-images.githubusercontent.com/23624044/90281642-8d8e7c80-de8a-11ea-9c3a-ddad405d5197.jpg)

**Comment by jagrit007** [comment]
Umm... You need to clone your Heroku app, add credentials, generate drive token and push back to Heroku. I didn't think this through while making the one-click deploy button. Will figure a work-around soon. For now, the above mentioned should do the job.

**Comment by jagrit007** [comment]
Hope this README file update helps.
https://github.com/jagrit007/Telegram-CloneBot#running

**Comment by haxshaan** [comment]
I am also trying to deploy the bot on Heroku using Deploy button. 

I have successfully cloned the git repo and copied credentials.json and token.pickle file to the local git repo folder.

But when I try to commit the files and push using command `git push heroku master` it gives and error.

Logs:
`/home/drive/drive-clone$ git push heroku master
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 1.10 KiB | 1.10 MiB/s, done.
Total 4 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to drive-clone.
remote: 
To https://git.heroku.com/drive-clone.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/drive-clone.git'
`

**Comment by haxshaan** [comment]
I have **fixed** above error by including an empty 'requirements.txt' file.

**Comment by haxshaan** [comment]
> I am also trying to deploy the bot on Heroku using Deploy button.
> 
> I have successfully cloned the git repo and copied credentials.json and token.pickle file to the local git repo folder.
> 
> But when I try to commit the files and push using command `git push heroku master` it gives and error.
> 
> Logs:
> 
> ```
> /home/drive/drive-clone$ heroku git:clone -a drive-clone
>  ›   Warning: heroku update available from 7.42.4 to 7.42.8.
> Cloning into 'drive-clone'...
> warning: You appear to have cloned an empty repository.
> 
> /home/drive/drive-clone$ cd drive-clone
> 
> /home/drive/drive-clone$ ls
> credentials.json  token.pickle
> 
> /home/drive/drive-clone$ git add .
> 
> /home/drive/drive-clone$ git commit -m "credential file added"
> [master (root-commit) a374040] credentials and token
>  2 files changed, 1 insertion(+)
>  create mode 100644 credentials.json
>  create mode 100644 token.pickle
> 
> /home/drive/drive-clone$ git push heroku master
> Enumerating objects: 4, done.
> Counting objects: 100% (4/4), done.
> Delta compression using up to 4 threads
> Compressing objects: 100% (4/4), done.
> Writing objects: 100% (4/4), 1.10 KiB | 1.10 MiB/s, done.
> Total 4 (delta 0), reused 0 (delta 0)
> remote: Compressing source files... done.
> remote: Building source:
> remote: 
> remote: -----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz
> remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
> remote: 
> remote:  !     Push failed
> remote: Verifying deploy...
> remote: 
> remote: !	Push rejected to drive-clone.
> remote: 
> To https://git.heroku.com/drive-clone.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.heroku.com/drive-clone.git
> ```

I have fixed above error by including an empty 'requirements.txt' file

**Comment by begginer-123** [comment]
@jagrit007 Hello Sir, I just have one question. Can we add the token.pickle and credentials.json file before we deploy it to heroku

**Comment by jagrit007** [comment]
> @jagrit007 Hello Sir, I just have one question. Can we add the token.pickle and credentials.json file before we deploy it to heroku

Yes, you can.
Just clone it to a local system or termux or Repl.it
Install requirements; 
`pip3 install -r requirements.txt`
and then follow the rest of the instructions from ReadME file.
After you generate it all, you could push directly to  Heroku or make a private repo and push it there and connect that to Heroku.

**Comment by askfriends** [comment]
token and credential is necessary?
cant we add var for rclone config and heroku?

**Comment by jagrit007** [comment]
> 
> 
> token and credential is necessary?

Yes.

> cant we add var for rclone config and heroku?

No.


"Tip: Instead of using Termux or local machine, use repl.it, atleast it won't throw any errors in installing Python requirements. From repl.it you could push to a private GitHub repo and attach that to Heroku." (https://github.com/jagrit007/Telegram-CloneBot#running)

**Comment by askfriends** [comment]
> repl.it

i see..
btw can you edit your readme? its bit confusing.
you should add step by step  info for deploying it on vps and heroku separately.

thanks anyway

**Comment by jagrit007** [comment]
Video Guide:

https://github.com/jagrit007/Telegram-CloneBot/blob/master/README.md#guide
